[package]
name = "rita"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
babel_monitor = { path = "../babel_monitor" }
althea_kernel_interface = { path = "../althea_kernel_interface" }
traffic_watcher = { path = "./traffic_watcher"}
tunnel_manager = { path = "./tunnel_manager"}
payment_controller = { path = "./payment_controller" }
debt_keeper = { path = "./debt_keeper" }
ip_network = "0.1"
log = "0.3"
docopt = "0.8.1"
simple_logger = "0.4.0"

[workspace]